# Generated by Django 3.0.8 on 2020-07-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100)),
                ('NumberOfRooms', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
