# Generated by Django 3.0.2 on 2020-07-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='r1',
            field=models.ImageField(blank='true', upload_to='site_media'),
        ),
    ]
