# Generated by Django 3.0.2 on 2020-07-28 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0003_auto_20200728_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='im2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='im3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='im4',
        ),
    ]
