# Generated by Django 3.0.2 on 2020-07-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0004_auto_20200728_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='im2',
            field=models.ImageField(blank='true', upload_to='site_media'),
        ),
        migrations.AddField(
            model_name='room',
            name='im3',
            field=models.ImageField(blank='true', upload_to='site_media'),
        ),
        migrations.AddField(
            model_name='room',
            name='im4',
            field=models.ImageField(blank='true', upload_to='site_media'),
        ),
    ]
