# Generated by Django 3.0.2 on 2020-07-28 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0005_auto_20200728_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='r1',
        ),
    ]
