# Generated by Django 3.0.2 on 2020-07-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0006_remove_room_r1'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lender_contact',
            field=models.CharField(default=20, max_length=100),
            preserve_default=False,
        ),
    ]
